# Generated by Django 3.2.18 on 2024-10-04 07:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotel_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.hotel_image_path),
        ),
    ]
